title: Johnny Nava
author: Johnny Nava
email: johnny.nava@gmail.com
description: "Personal blog/portfolio site."

highlighter: null
permalink: /:title

url: "http://mharr171.github.io"
baseurl: "/johnny-nava"

# Custom options:
# color_scheme: azul|ruby|amber|avocado|mint

color_scheme: mint
