title: Johnny Nava
author: Johnny Nava
email: johnny@heresjohnnynava.com
description: "Personal blog/portfolio site."

highlighter: null
permalink: /:title

url: "http://heresjohnnynava.com"
#url: "http://mharr171.github.io"
#http://mharr171.github.io
baseurl: ""
#/johnny-nava ??

# Custom options:
# color_scheme: azul|ruby|amber|avocado|marigold

color_scheme: marigold
